### ISSUE TITLE
How do you make the lightbox fullscreen?

### ISSUE THREAD

**Issue by jackson-sandland** [Ngineer101/react-image-video-lightbox#9]
I've tried a few different ways to make the light box full screen with no luck.
```
      <Container style={{ padding: 0 }} maxWidth={true}>
        <ReactImageVideoLightbox
        data={[
            { url: "https://www.youtube.com/embed/ScMzIvxBSi4", type: 'video', altTag: 'some video' },
            { url: s3URL, type: 'video', altTag: 'some video' },
            { url: s3URL, type: 'video', altTag: 'some video' },
            { url: s3URL, type: 'video', altTag: 'some video' },
            { url: s3URL, type: 'video', altTag: 'some video' },
            { url: s3URL, type: 'video', altTag: 'some video' },
            { url: s3URL, type: 'video', altTag: 'some video' },
            { url: s3URL, type: 'video', altTag: 'some video' }
        ]}
        startIndex={0}
        className={classes.playerWrapper}
        classes={{
          video: classes.playerWrapper,
          iframe: classes.playerWrapper
        }}
        onCloseCallback={callbackFunction} />
      </Container>
```
Here are my styles: 
```
const useStyles = makeStyles((theme) => ({
  root: {
    backgroundColor: "black",
    minHeight: "100%"
  },
	playerWrapper: {
		width: "100vw",
		height: "56.25vw",
		overflow: "hidden",
		background: "black",
		maxHeight: "100vh",
		maxWidth: "177.78vh",
		margin: "auto",
		position: "absolute",
		top: 0,
		bottom: 0,
		left: 0,
		right: 0
	},
	player: {
		position: "absolute",
		top: 0,
		left: 0
	}
}));
```
I've even tried changing the hard coded dimensions in the minified js.

How do you get the light box to default to full screen?

**Comment by maribelbhf** [comment]
Hi, there!

I had the same issue and I just changed the lightbox container height, width and z-index using useEffect. I also hid the overflow while its opened and added a scrollIntoView function to take me to the top once the lightbox container is open (thats where the lightbox container is bc of its absolute position)  and take me back to my carousel when its closed.

`useEffect(() => { 
  const LightboxContainer = document.querySelector('#parent to ReactImageVideoLightbox container ')
  const HtmlContainer = document.querySelector('html')
 
  var top = LightboxContainer.offsetTop; 


 if (lightboxOpen === true){
  LightboxContainer.firstChild.style.zIndex = 100
  LightboxContainer.firstChild.style.height =' 100vh'
  LightboxContainer.firstChild.style.width = '100vw'
  HtmlContainer.style.overflowY= 'hidden'
  LightboxContainer.firstChild.scrollIntoView()
  
 }else{
  LightboxContainer.firstChild.style.zIndex = 20
  HtmlContainer.style.overflowY= 'scroll'
  window.scrollTo(0, top); 
  
 } `

**Comment by Ngineer101** [comment]
Just to clarify - when you say you want to make the lightbox fullscreen, are you referring to the images and videos displayed inside the lightbox?

The lightbox itself (with black background) should always cover the entire screen regardless of size.

**Comment by taimoortahir7** [comment]
No, it sees full screen when there is no scroll in page.
If there is content more than default dimensions of screen, the lightbox only occupies the default portion of screen and rest of screen is not occupied
